services:
  stylophonix:
    volumes:
      - /mnt/cdn/stylophonix/data/data/:/app/wwwroot/data
      - /mnt/cdn/stylophonix/data/img/gigs:/app/wwwroot/img/gigs
      - /mnt/cdn/stylophonix/data/img/lineup:/app/wwwroot/img/lineup
      - /mnt/cdn/stylophonix/data/img/news:/app/wwwroot/img/news
      - /mnt/cdn/stylophonix/data/img/music:/app/wwwroot/img/music
    networks:
      - reverse-proxy
    labels:
      caddy: stylophonix.de
      caddy.reverse_proxy: "{{upstreams 8080}}"
  
  filebrowser:
    image: filebrowser/filebrowser
    container_name: stylophonix-filebrowser
    restart: unless-stopped
    volumes:
      - /mnt/cdn/stylophonix/data:/srv
      - /opt/stylophonix/filebrowser:/database
    networks:
      - reverse-proxy
    labels:
      caddy: ${EXTERNAL_URL_FILEBROWSER}
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  reverse-proxy:
    external: true