services:
  stylophonix:
    ports:
      - "8080:8080"
    volumes:
      - ./data/data/:/app/wwwroot/data
      - ./data/img/gigs:/app/wwwroot/img/gigs
      - ./data/img/lineup:/app/wwwroot/img/lineup
      - ./data/img/news:/app/wwwroot/img/news
      - ./data/img/music:/app/wwwroot/img/music
    labels:
      - dev.orbstack.domains=stylophonix.local