services:
  stylophonix:
    volumes:
      - ./data/data/:/app/wwwroot/data
      - ./data/img/gigs:/app/wwwroot/img/gigs
      - ./data/img/lineup:/app/wwwroot/img/lineup
      - ./data/img/news:/app/wwwroot/img/news
      - ./data/img/music:/app/wwwroot/img/music
    networks:
      - caddy
    labels:
      caddy: stylophonix.xyz, stylophonix.tawmy.dev
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true