services:
  stylophonix:
    networks:
      - caddy
    labels:
      caddy: stylophonix.xyz, stylophonix.dev.tawmy.dev
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true