# This is a generated file. Not intended for manual editing.
services:
  stylophonix:
    build:
      context: "/Users/tawmy/Git/Stylophonix"
      dockerfile: "Stylophonix/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/Stylophonix.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net7.0/Stylophonix.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "/Users/tawmy/.nuget/packages"
      NUGET_FALLBACK_PACKAGES: "/Users/tawmy/.nuget/packages"
    image: "stylophonix:dev"
    ports: []
    volumes:
    - "/Users/tawmy/.nuget/packages:/root/.nuget/fallbackpackages"
    - "/Users/tawmy/Git/Stylophonix/Stylophonix:/app:rw"
    - "/Users/tawmy/Git/Stylophonix:/src:rw"
    working_dir: "/app"
